aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
concurrency: 1
# When a queue gets empty, the queue will be paused for the number of seconds specified in delay
delay: 20
queues:
  - [default, 10]
  - [dlq, 5]